services:
  django:
    build: ./django-app
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,*
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      # Hardcoded IP for Host
      - N8N_HOST=100.28.228.132
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      # Hardcoded IP for Webhook URL
      - WEBHOOK_URL=http://100.28.228.132:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
